app = "cyc-inwgra"
primary_region = "iad"

[build]
    builder = "paketobuildpacks/builder:base"
    buildpacks = ["paketobuildpacks/java"]

[build.args]
    BP_JVM_VERSION = "21"

[vm]
    cpu_kind = "shared"
    cpus = 1
    memory_mb = 512

[http_service]
    internal_port = 8080
    force_https = true
    auto_stop_machines = "stop"
    auto_start_machines = true
    min_machines_running = 0
    processes = ["app"]